Merge latest from upstream
dnnsoftware/ClientDependency pull request #10
Opened 2021-08-10 20:38 UTC by bdukes

This repo is currently based on the 1.9.2 release of https://github.com/Shazwazza/ClientDependency.

This PR includes changes from 1.9.3 to 1.9.10.

2021-08-11 01:14 UTC, valadas requested changes
Looks about right to me except one little note

2021-08-11 01:14 UTC, valadas commented on src/ClientDependency.Core/CompositeFiles/CompositeDependencyHandler.cs
> -                    if (context.IsDebuggingEnabled || dnnConfig.IsDebugMode())
I think we loose the DNN debug mode here with this change...

2021-08-11 14:02 UTC, bdukes commented on src/ClientDependency.Core/CompositeFiles/CompositeDependencyHandler.cs
> -                    if (context.IsDebuggingEnabled || dnnConfig.IsDebugMode())
I've added back a logger statement here. Other places we were doing a similar thing have been replaced with calls to `ClientDependencySettings.Instance.Logger`. I think we may want to implement a DNN Logger to get those messages into our logging infrastructure. But that would be a change in Dnn.Platform, not here.

2021-08-12 18:34 UTC, mitchelsellers approved these changes

2021-08-12 18:34 UTC, merged